### ISSUE TITLE
Where is the mentioned PDF?

### ISSUE THREAD

**Issue by tad** [bigmachine-io/mission-interview#4]
This is probably a dumb question, but several times in the Data Structures video, you mention referring to a PDF. I don't see it.

Maybe it's really obvious, but if you can, please let me know where it lives. :)

Thanks!

**Comment by tad** [comment]
So, I think the PDF is a portion of the book. I own the book, so I guess that's ok, but can you please let me know which section of the book, exactly I should look at?

**Comment by robconery** [comment]
Crap! Sorry I didn't reply before ... my notifications are all screwy. YES - the PDF is a part of the book itself. I decided to throw that in for completeness sake.
