### ISSUE TITLE
Islands In The Sea - setSail Improvement

### ISSUE THREAD

**Issue by sagivf** [bigmachine-io/mission-interview#9]
I believe that when you `setSail` there is no need to go over land that has already been sailed and mapped. Am I correct?
``` javascript
  let lat = 0
  let lon = 0
  const setStail = () => {
    for (; lat < ocean.length; lat++) {
      for (; lon < ocean[lat].length; lon++) {
        if (ocean[lat][lon] === 1) {
          return {lat, lon}
        }
      }
      lon = 0;
    }
    return false
  }
``

**Comment by robconery** [comment]
I think it might save on some things but I don't think it effects the overall time complexity. Either way - nice tweak :).

**Comment by sagivf** [comment]
I believe your correct, just wanted to see I wasn't missing anything, thanks :)
